'use strict';

var keyMirror = require('react/lib/keyMirror');

module.exports = keyMirror({
    GET_BACKUPS: null,
    GET_BACKUPS_SUCCESS: null,
    GET_BACKUPS_FAIL: null,
    ADD_BACKUP: null,
    ADD_BACKUP_SUCCESS: null,
    ADD_BACKUP_FAIL: null,
    RESTORE_FROM_BACKUP: null,
    REQUEST_MENUPOINTS: null,
    SET_NEXT_TRANSITION: null,
    RESET_TRANSITION: null,
    TOGGLE_MENU: null,
    CLOSE_MENU: null,
    OPEN_MODAL: null,
    CLOSE_MODAL: null,
    SET_HEADER_CONFIG: null,
    RESET_HEADER_CONFIG: null,
    GET_EXERCISES: null,
    ADD_EXERCISE: null,
    REMOVE_EXERCISE: null,
    UPDATE_EXERCISE: null,
    GET_WORKOUTS: null,
    ADD_WORKOUT: null,
    REMOVE_WORKOUT: null,
    UPDATE_WORKOUT: null,
    START_TRAINING: null,
    FINISH_TRAINING: null,
    ADD_TRAINING: null,
    REMOVE_TRAINING: null,
    SET_CURRENT_EXERCISE: null,
    START_TIMER: null,
    STOP_TIMER: null,
    ADD_SET: null,
    REMOVE_SET: null,
    REMOVE_EXERCISE_FROM_WORKOUTS: null
});
